### ISSUE TITLE
Optimization step & DVH issue

### ISSUE THREAD

**Issue by adrianamaria** [e0404/matRad#44]
Hello,

Happy to report the resolution adjustments lowered the computational requirements and was able to get the first results.

On the other hand, the Optimization step had encountered the error which i will be listing below. Does it have to do with the Objective function-penalty-parameter i have chosen for my VOIs?
Consequently, the DVH has been plotted, but the mean/max/min dose for each VOI wasn't printed in the Command window.

Iteration 51: alpha = 1.000000, Obj func = 664.479890
Starting line search .
Iteration 52: alpha = 1.000000, Obj func = 662.653488
Starting line search Index exceeds matrix dimensions.

Error in matRad_daoVec2ApertureInfo (line 110)
        bixelIndRightLeaf = apertureInfo.beam(i).bixelIndMap((xPosIndRightLeaf-1)*n+[1:n]');

Error in matRad_daoObjFunc (line 48)
apertureInfo = matRad_daoVec2ApertureInfo(apertureInfo,apertureInfoVect);

Error in matRad_directApertureOptimization>@(x)matRad_daoObjFunc(x,apertureInfo,dij,cst) (line 65)
objFunc =  @(x) matRad_daoObjFunc(x,apertureInfo,dij,cst);

Error in matRad_projectedLBFGS (line 161)
        [lineSearchObjFuncValue,lineSearchDx] = objFunc(candidateX);

Error in matRad_directApertureOptimization (line 74)
optApertureInfoVec = matRad_projectedLBFGS(objFunc,projFunc,initApertureInfoVec,visBool,varargin);

Error in matRadGUI>btnOptimize_Callback (line 1203)
   resultGUI = matRad_directApertureOptimization(evalin('base','dij'),evalin('base','cst')...

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRadGUI (line 66)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)matRadGUI('btnOptimize_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating UIControl Callback

Many thanks,
Adriana

**Comment by markbangert** [comment]
Hi Adiriana,

glad to hear you are making progress. The error you are reporting really
sounds like a bug in our code. I am not super surprised about that I have
to say because the direct aperture optimization engine really has to be
considered somewhat experimental ;)

Are you able to share the matlab workspace including ct,cst,pln and - if
not to big also dij - so I can run matRad to try and reporduce your error?
That would really speed up things I guess. You can use my email
m.bangert@dkfz.de for private conversation!

Cheers / Mark

**Comment by markbangert** [comment]
Hi Adriana,

thanks for sending your files to my dkfz email. I downloaded everything and ran

   resultGUI = matRad_directApertureOptimization(dij,cst,resultGUI.apertureInfo,resultGUI);

in the command prompt. I was not able to reproduce your error but I got a different error message that reads

---
Subscript indices must either be real positive integers or logicals.

Error in matRad_daoObjFunc (line 79)
    g(apertureInfo.totalNumOfShapes+1:end) = ...

Error in
matRad_directApertureOptimization>@(x)matRad_daoObjFunc(x,apertureInfo,dij,cst)
(line 65)
objFunc =  @(x) matRad_daoObjFunc(x,apertureInfo,dij,cst);

Error in matRad_projectedLBFGS (line 165)
        [lineSearchObjFuncValue,lineSearchDx] = objFunc(candidateX);

Error in matRad_directApertureOptimization (line 74)
optApertureInfoVec =
matRad_projectedLBFGS(objFunc,projFunc,initApertureInfoVec,visBool,varargin);
---

I will investigate and update you as soon as I know more.

Mark

**Comment by markbangert** [comment]
Alright. I have identified a numerical instability thanks to your help within the computation of the leaf position gradients during direct aperture optimization. I just pushed a fix to the dev branch. The only file that has been modified is https://github.com/e0404/matRad/blob/dev/matRad_daoVec2ApertureInfo.m. Could you please check it out and let me know if that also solves your issues with DAO?

Thanks! Mark

**Comment by adrianamaria** [comment]
Mark, thank you again for the prompt replies and all the help.

I've modified the file and ran everything with the same variables. This error came up:
Iteration 114: alpha = 0.100000, Obj func = 0.623488

114 iteration(s) performed to converge
Error using matRad_daoApertureInfo2Vec
Too many output arguments.

Error in matRad_sequencing2ApertureInfo (line 191)
[apertureInfo.apertureVector, apertureInfo.mappingMx, apertureInfo.limMx] = matRad_daoApertureInfo2Vec(apertureInfo);

Error in matRad_engelLeafSequencing (line 388)
resultGUI.apertureInfo = matRad_sequencing2ApertureInfo(sequencing,stf);

Error in matRadGUI>btnOptimize_Callback (line 1196)
    resultGUI = matRad_engelLeafSequencing(resultGUI,evalin('base','stf'),evalin('base','dij')...

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRadGUI (line 66)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)matRadGUI('btnOptimize_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating UIControl Callback

Conversion to logical from struct is not possible.

Error in matRad_engelLeafSequencing (line 57)
if visBool

Error in matRadGUI>btnSequencing_Callback (line 2175)
    resultGUI = matRad_engelLeafSequencing(resultGUI.w,evalin('base','stf'),evalin('base','dij')...

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRadGUI (line 66)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)matRadGUI('btnSequencing_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating UIControl Callback

Cheers,
Adriana

**Comment by markbangert** [comment]
This does not make sense to me. Can you try rerunning everything from
scratch with the same ct and cst?
Am 07.01.2016 10:04 schrieb "adrianamaria" <notifications@github.com>:

**Comment by adrianamaria** [comment]
Hi Mark,

As a matter of fact i did.
Here's a more unconventional way of showing you the workflow that led me to the error.
If there is some corrupt step along the way, let me know.
Please note that i've tried running everything from scratch as well (loading the dicom data all over again), still the same error.

https://adriana-gmail.tinytake.com/sf/NDQyMTAyXzIzOTc1MDU

Thank you,
Adriana

**Comment by markbangert** [comment]
Ah. Thanks for the video! Now I see that you are now crashing not
during/after DAO but during sequencing after the conventional fluence
optimization. I will look into this tonight. No time right now...

**Comment by markbangert** [comment]
Hi Adriana, I just had a look at the issue again and unfortunately I still could not reproduce your error. I am not 100% sure we are using the same code base at the moment. I would like to ask you to get a fresh copy of matRad from the dev branch. You can either go via https://github.com/e0404/matRad/tree/dev or use this link for a direct download of a zip file https://github.com/e0404/matRad/archive/dev.zip.

Then I would like you to load variable.mat you sent me and delete everything but ct and cst. next start matRadGUI and rerun everything. In particular you need to delete the pln struct because we had some changes recently that do not work with your old pln struct. Let me know if the error still shows up.

Also I would like to know which matlab version you are using on which operating system.

Thanks / Mark

**Comment by markbangert** [comment]
Also as you have been asking about the meaning of the optimization parameters I have added some more detail in our wiki at https://github.com/e0404/matRad/wiki/How-to-execute-matRadGUI#set-optimization-parameters.

**Comment by adrianamaria** [comment]
Mark,

I've re-downloaded the matRAD, used only the ct&cst variables (having deleted pln this time) and ran the whole thing again, as instructed.
This time, it worked! So many thanks!
The only thing that is missing would be the min/max dose for each VOI  in the command window, after having plotted DVH.

Adriana

**Comment by markbangert** [comment]
Great to hear everything is working now. If you want to have dose stats aswell you need to run https://github.com/e0404/matRad/blob/master/matRad_calcQualityIndicators.m as we moved the computation into a separate function that gives you more flexibility (you can also compute dose volume points, homogeneity indices and confomity indices).

I will close this issue now. Thanks for your input it helped make the DAO engine more stable with regard to numerical pronblems during rounding operations.

As you are working with the direct aperture optimization engine I wanted to let you know that you should be aware of the fact that our sequencing algorithms do not incorporate any field size constraints to obtain nicer (i.e. not disconnected and small) shapes. The direct aperture optimzation does not correct for this short coming so the shapes you might be working with are not exactly deliverable. As matRad is primarliy developed for particles on our side we are not actively improving this at the moment. If somebody wants to contribute we would be very happy about any help :)

**Comment by markbangert** [comment]
Also be aware that we merged all changes in the dev branch into the master to have a coherent code base again.
